name: push_service_interface
description: Remote push service interface
version: 0.1.2
publish_to: none

environment:
  sdk: ^3.3.4

dependencies:
  flutter:
    sdk: flutter

  base_service_interface:
    path: ../base_service_interface
  shared_preferences: ^2.2.3 # Android background and 'killed' push messages callback handler support # Last 3.3.0 version - 2.2.3
  universal_platform: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
