name: errlog_service_gms
description: Internal GMS error log service (Firebase Crashlytics)
version: 0.1.2
publish_to: none

environment:
  sdk: ^3.3.4

dependencies:
  flutter:
    sdk: flutter

  errlog_service_interface:
    path: ../../../mobile_service_interface/errlog_service_interface
  universal_platform: ^1.1.0
  firebase_core: ^3.4.0 # Last 3.3.0 version - 3.4.0
  firebase_crashlytics: ^4.1.0 # Last 3.3.0 version - 4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any