name: errlog_service_gms
description: Internal GMS error log service (Firebase Crashlytics)
version: 0.1.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  errlog_service_interface:
    path: ../../../mobile_service_interface/errlog_service_interface
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any