name: example
description: "Mobile services use case example"

publish_to: 'none'

version: 1.0.3+6

environment:
  sdk: ^3.0.0

# https://yaml.org/refcard.html
analytics_service_path: &analytics_service_path ../gms_only/analytics_service # YAML anchor
errlog_service_path: &errlog_service_path ../gms_only/errlog_service # YAML anchor
push_service_path: &push_service_path ../gms_only/push_service # YAML anchor

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Native payload plugins
  device_info_plus: ">=9.0.0 <12.0.0" # Feedback info carver # Last 3.3.0 version - 10.1.2
  package_info_plus: ">=4.2.0 <9.0.0" # Last 3.3.0 version - 8.0.2

  #Native UI plugins
  flutter_statusbarcolor_ns: #0.5.0 # Native status bar controller (iOS Background color support)
    git: # Android gradle namespace error fix
      url: 'https://github.com/Schefferbird/flutter_statusbarcolor'
      ref: '3bf3bff39ca40008c8703830067b3daffe7dc4cb' # 18.06.24

  #UI modules
  flutter_svg: ^2.0.10+1 # SVG render engine # Last 3.3.0 version - 2.0.10+1

  analytics_service:
    path: *analytics_service_path
  errlog_service:
    path: *errlog_service_path
  push_service:
    path: *push_service_path

  intl: any # Localization plugin

#dependency_overrides:
  #huawei_push:
    #git:
      #url: https://github.com/crasowas/hms-flutter-plugin.git
      #path: flutter-hms-push

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: any

  # Setup: pub global activate flutter_asset_generator
  flutter_asset_generator: 1.2.0 # Assets map generator (fgen --no-watch --no-preview -n R -o lib/generated/assets.dart)

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  enabled: true