name: analytics_service
description: "HMS-only analytics service"
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  analytics_service_hms:
    path: ../../mobile_service_component/analytics_service/analytics_service_hms