name: analytics_service
description: "GMS-only analytics service (Firebase)"
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

repository_url: &repository_url https://github.com/mIwr/mobile_service
repository_ref: &repository_ref master
analytics_service_path: &analytics_service_path mobile_service_component/analytics_service/analytics_service_gms

dependencies:
  flutter:
    sdk: flutter

  analytics_service_gms:
    git:
      url: *repository_url
      ref: *repository_ref
      path: *analytics_service_path