name: analytics_service
description: "GMS-only analytics service (Firebase)"
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  analytics_service_gms:
    path: ../../mobile_service_component/analytics_service/analytics_service_gms