name: base_multi_service_interface
description: Base mobile multi-service interface
version: 0.1.3
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

repository_url: &repository_url https://github.com/mIwr/mobile_service
repository_ref: &repository_ref master
base_service_path: &base_service_path mobile_service_interface/base_service_interface

dependencies:

  base_service_interface:
    git:
      url: *repository_url
      ref: *repository_ref
      path: *base_service_path

dev_dependencies:
  lints: any # Last 3.3.0 version - 4.0.0
  test: ^1.21.6 # Last 3.3.0 version - 1.25.7
