name: analytics_service
description: Combined (GMS [priority and default] + HMS [reserve, if GMS isn't available]) analytics service
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  analytics_service_interface:
    path: ../../mobile_service_interface/analytics_service_interface
  analytics_service_gms:
    path: ../../mobile_service_component/analytics_service/analytics_service_gms
  analytics_service_hms:
    path: ../../mobile_service_component/analytics_service/analytics_service_hms
  flutter_hms_gms_availability: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any