name: errlog_service
description: Combined (GMS [priority and default] + HMS [reserve, if GMS isn't available]) error log service
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

repository_url: &repository_url https://github.com/mIwr/mobile_service
repository_ref: &repository_ref master
errlog_service_path: &errlog_service_path mobile_service_interface/errlog_service_interface
errlog_service_gms_path: &errlog_service_gms_path mobile_service_component/errlog_service/errlog_service_gms
errlog_service_hms_path: &errlog_service_hms_path mobile_service_component/errlog_service/errlog_service_hms

dependencies:
  flutter:
    sdk: flutter

  flutter_hms_gms_availability: ^3.7.0
  errlog_service_interface:
    git:
      url: *repository_url
      ref: *repository_ref
      path: *errlog_service_path
  errlog_service_gms:
    git:
      url: *repository_url
      ref: *repository_ref
      path: *errlog_service_gms_path
  errlog_service_hms:
    git:
      url: *repository_url
      ref: *repository_ref
      path: *errlog_service_hms_path

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any