name: analytics_service_gms
description: Internal GMS analytics service (Firebase)
version: 0.1.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

repository_url: &repository_url https://github.com/mIwr/mobile_service
repository_ref: &repository_ref master
analytics_service_path: &analytics_service_path mobile_service_interface/analytics_service_interface

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.2.0
  firebase_analytics: ^11.2.0
  analytics_service_interface:
    git:
      url: *repository_url
      ref: *repository_ref
      path: *analytics_service_path

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
