name: errlog_service_sentry
description: Internal Sentry error log service
version: 0.1.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

repository_url: &repository_url https://github.com/mIwr/mobile_service
repository_ref: &repository_ref master
errlog_service_path: &errlog_service_path mobile_service_interface/errlog_service_interface

dependencies:
  flutter:
    sdk: flutter

  sentry_flutter: ^8.4.0
  errlog_service_interface:
    git:
      url: *repository_url
      ref: *repository_ref
      path: *errlog_service_path

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any