name: errlog_service_sentry
description: Internal Sentry error log service
version: 0.1.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  errlog_service_interface:
    path: ../../../mobile_service_interface/errlog_service_interface
  sentry_flutter: ^8.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any