name: errlog_service_hms
description: Internal HMS error log service
version: 0.1.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  errlog_service_interface:
    path: ../../../mobile_service_interface/errlog_service_interface
  agconnect_crash: # 1.9.0+300 # No Android SDK 34 support
    git: # Android SDK 34 support fix
      url: 'https://github.com/julio-lezcano-itti/agc-flutter-plugin'
      ref: '4dce9b0159d56df8d13249d675c90ab25dc37e16'
      path: 'agconnect_crash/'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any