name: analytics_service_hms
description: Internal HMS analytics service
version: 0.1.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

repository_url: &repository_url https://github.com/mIwr/mobile_service
repository_ref: &repository_ref master
analytics_service_path: &analytics_service_path mobile_service_interface/analytics_service_interface

dependencies:
  flutter:
    sdk: flutter

  huawei_analytics: # 6.12.0+301 # No Android SDK 34 support
    git: # Android SDK 34 support fix
      url: 'https://github.com/julio-lezcano-itti/hms-flutter-plugin'
      ref: '9ddd3b8433689f454072606108717d9eda07b1f7'
      path: 'flutter-hms-analytics/'
  analytics_service_interface:
    git:
      url: *repository_url
      ref: *repository_ref
      path: *analytics_service_path

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any