name: analytics_service_app_metrica
description: Internal Yandex App Metrica analytics service
version: 0.1.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

repository_url: &repository_url https://github.com/mIwr/mobile_service
repository_ref: &repository_ref master
analytics_service_path: &analytics_service_path mobile_service_interface/analytics_service_interface

dependencies:
  flutter:
    sdk: flutter

  appmetrica_plugin: ^2.1.1
  analytics_service_interface:
    git:
      url: *repository_url
      ref: *repository_ref
      path: *analytics_service_path

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any