name: errlog_service_app_metrica
description: Internal Yandex App Metrica error log service
version: 0.1.2
publish_to: none

environment:
  sdk: ^3.3.4

dependencies:
  flutter:
    sdk: flutter

  errlog_service_interface:
    path: ../../../mobile_service_interface/errlog_service_interface
  universal_platform: ^1.1.0
  appmetrica_plugin: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any