name: errlog_service_app_metrica
description: Internal Yandex App Metrica error log service
version: 0.1.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  errlog_service_interface:
    path: ../../../mobile_service_interface/errlog_service_interface
  appmetrica_plugin: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any