name: analytics_service_interface
description: Remote analytics service interface
version: 0.1.2
publish_to: none

environment:
  sdk: ^3.3.4

repository_url: &repository_url https://github.com/mIwr/mobile_service
repository_ref: &repository_ref master
base_service_path: &base_service_path mobile_service_interface/base_service_interface

dependencies:

  base_service_interface:
    git:
      url: *repository_url
      ref: *repository_ref
      path: *base_service_path

dev_dependencies:
  lints: any # Last 3.3.0 version - 4.0.0
  test: ^1.25.7 # Last 3.3.0 version - 1.25.7
