name: analytics_service_interface
description: Remote analytics service interface
version: 0.1.3
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:

  base_service_interface:
    path: ../base_service_interface

dev_dependencies:
  lints: any
  test: ^1.21.6
