name: analytics_service_interface
description: Remote analytics service interface
version: 0.1.2
publish_to: none

environment:
  sdk: ^3.3.4

dependencies:

  base_service_interface:
    path: ../base_service_interface

dev_dependencies:
  lints: any # Last 3.3.0 version - 4.0.0
  test: ^1.25.7 # Last 3.3.0 version - 1.25.7
