name: push_service_hms
description: Internal HMS push service
version: 0.1.3
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

repository_url: &repository_url https://github.com/mIwr/mobile_service
repository_ref: &repository_ref master
push_service_path: &push_service_path mobile_service_interface/push_service_interface

dependencies:
  flutter:
    sdk: flutter

  huawei_push: ^6.13.0+300 #
    # git: # Not found ShimPluginRegistry fix
      # url: https://github.com/crasowas/hms-flutter-plugin.git
      # path: flutter-hms-push
    #git: # Android SDK 34 support fix + delete Android deprecated Registrar methods
      #url: 'https://github.com/julio-lezcano-itti/hms-flutter-plugin'
      #path: 'flutter-hms-push/'
    #git:
      #url: 'https://github.com/yashadpf/hms-flutter-plugin'
      #path: 'flutter-hms-push/'
  push_service_interface:
    git:
      url: *repository_url
      ref: *repository_ref
      path: *push_service_path

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any