name: push_service_hms
description: Internal HMS push service
version: 0.1.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  push_service_interface:
    path: ../../../mobile_service_interface/push_service_interface
  huawei_push: #6.12.0+301 # No Android SDK 34 support
    git:
      url: 'https://github.com/yashadpf/hms-flutter-plugin'
      ref: '78da3906c32c3b99e0a3fa4af3fb5f003f9e573f'
      path: 'flutter-hms-push/'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any